name: qatrah_app
description: "Qatrah water usage tracking app (Flutter + Bluetooth + Mock Data)"
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # BLE & permissions
  flutter_blue_plus: ^1.36.8
  permission_handler: ^11.3.1
  device_info_plus: ^11.1.0

  # State & Navigation
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1

  # Data & storage
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  path_provider: ^2.1.5

  # Utilities
  intl: ^0.19.0
  cached_network_image: ^3.3.1

  # UI
  flutter_svg: ^2.0.9
  fl_chart: ^0.69.2
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/logo.png

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
